apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: mern-app
  namespace: argocd
spec:
  interval: 2m
  applications:
    - name: mern-app
      namespace: argocd
      images:
        - name: api
          image: ritesh57/api-gateway
          helm:
            valuePath: services.api-gateway.image.tag
        - name: auth
          image: ritesh57/auth-service
          helm:
            valuePath: services.auth-service.image.tag
        - name: order
          image: ritesh57/order-service
          helm:
            valuePath: services.order-service.image.tag
        - name: frontend
          image: ritesh57/frontend
          helm:
            valuePath: services.frontend.image.tag
      update:
        strategy: latest
        writeBack:
          method: git
          git:
            branch: main
